trigger: none
pr:
  branches:
    include:
      - '*'

name: terraform-lint

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    displayName: 'Check out code'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: "curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip && unzip terraform.zip && sudo mv terraform /usr/local/bin/ && terraform -version"
    displayName: 'Setup Terraform 1.1.7'

  - script: "terraform fmt -check"
    displayName: 'Terraform fmt'
    continueOnError: 'true'
    workingDirectory: test-case

  - script: "terraform init"
    displayName: 'Terraform Init'
    workingDirectory: test-case

  - script: "terraform validate"
    displayName: 'Terraform Validate'
    workingDirectory: test-case

  - script: "terraform plan -out=tfplan"
    displayName: 'Terraform Plan'
    continueOnError: 'true'
    workingDirectory: test-case

  - script: "if [ $? -eq 1 ]; then echo 'Terraform plan failed.'; exit 1; else echo 'Terraform plan succeeded.'; exit 0; fi"
    displayName: 'Exit status'
    failOnStderr: 'false'
    workingDirectory: test-case 